package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.SongsStyles;
import org.mybatis.cdi.Mapper;

@Mapper
public interface SongsStylesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONGS_STYLES
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    int insert(SongsStyles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONGS_STYLES
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    List<SongsStyles> selectAll();
}