package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Style;
import org.mybatis.cdi.Mapper;

@Mapper
public interface StyleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STYLE
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STYLE
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    int insert(Style record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STYLE
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    Style selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STYLE
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    List<Style> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STYLE
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    int updateByPrimaryKey(Style record);

    List<Style> selectStyleBySong(Integer studentsId);

    List<Style> selectStyleBySongFree(Integer studentsId);
}