package lt.vu.mybatis.model;

public class Album {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ALBUM.ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ALBUM.NAME
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ALBUM.ARTIST_ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    private Integer artistId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ALBUM.ID
     *
     * @return the value of PUBLIC.ALBUM.ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ALBUM.ID
     *
     * @param id the value for PUBLIC.ALBUM.ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ALBUM.NAME
     *
     * @return the value of PUBLIC.ALBUM.NAME
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ALBUM.NAME
     *
     * @param name the value for PUBLIC.ALBUM.NAME
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ALBUM.ARTIST_ID
     *
     * @return the value of PUBLIC.ALBUM.ARTIST_ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public Integer getArtistId() {
        return artistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ALBUM.ARTIST_ID
     *
     * @param artistId the value for PUBLIC.ALBUM.ARTIST_ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public void setArtistId(Integer artistId) {
        this.artistId = artistId;
    }
}