package lt.vu.mybatis.model;

public class Artist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARTIST.ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARTIST.NAME
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARTIST.ID
     *
     * @return the value of PUBLIC.ARTIST.ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARTIST.ID
     *
     * @param id the value for PUBLIC.ARTIST.ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARTIST.NAME
     *
     * @return the value of PUBLIC.ARTIST.NAME
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARTIST.NAME
     *
     * @param name the value for PUBLIC.ARTIST.NAME
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return String.format("%s[id=%d]", getClass().getSimpleName(), getId());
    }
}