package lt.vu.mybatis.model;

public class Song {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.LINK
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.NAME
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.ALBUM_ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    private Integer albumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.ARTIST_ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    private Integer artistId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.ID
     *
     * @return the value of PUBLIC.SONG.ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.ID
     *
     * @param id the value for PUBLIC.SONG.ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.LINK
     *
     * @return the value of PUBLIC.SONG.LINK
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.LINK
     *
     * @param link the value for PUBLIC.SONG.LINK
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.NAME
     *
     * @return the value of PUBLIC.SONG.NAME
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.NAME
     *
     * @param name the value for PUBLIC.SONG.NAME
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.ALBUM_ID
     *
     * @return the value of PUBLIC.SONG.ALBUM_ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public Integer getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.ALBUM_ID
     *
     * @param albumId the value for PUBLIC.SONG.ALBUM_ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.ARTIST_ID
     *
     * @return the value of PUBLIC.SONG.ARTIST_ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public Integer getArtistId() {
        return artistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.ARTIST_ID
     *
     * @param artistId the value for PUBLIC.SONG.ARTIST_ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public void setArtistId(Integer artistId) {
        this.artistId = artistId;
    }
}