package lt.vu.mybatis.model;

public class SongsStyles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONGS_STYLES.STYLES_ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    private Integer stylesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONGS_STYLES.SONGS_ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    private Integer songsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONGS_STYLES.STYLES_ID
     *
     * @return the value of PUBLIC.SONGS_STYLES.STYLES_ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public Integer getStylesId() {
        return stylesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONGS_STYLES.STYLES_ID
     *
     * @param stylesId the value for PUBLIC.SONGS_STYLES.STYLES_ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public void setStylesId(Integer stylesId) {
        this.stylesId = stylesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONGS_STYLES.SONGS_ID
     *
     * @return the value of PUBLIC.SONGS_STYLES.SONGS_ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public Integer getSongsId() {
        return songsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONGS_STYLES.SONGS_ID
     *
     * @param songsId the value for PUBLIC.SONGS_STYLES.SONGS_ID
     *
     * @mbg.generated Tue May 12 15:59:51 EEST 2020
     */
    public void setSongsId(Integer songsId) {
        this.songsId = songsId;
    }
}